name: Ruby

on:
  push:
    branches:
      - master
  pull_request: {}
  merge_group: {}

jobs:
  test:
    runs-on: "ubuntu-latest"
    strategy:
      fail-fast: false
      matrix:
        ruby: ['3.2', '3.3', '3.4', '4.0', head]
        rubyopt: [""]
        job:
          - test
        include:
          - ruby: head
            job: stdlib_test rubocop
          - ruby: "4.0"
            job: stdlib_test
          - ruby: "4.0"
            job: test
            rubyopt: "--enable-frozen-string-literal"
          - ruby: "4.0"
            job: stdlib_test
            rubyopt: "--enable-frozen-string-literal"
          - ruby: "4.0"
            job: rubocop validate test_doc build test_generate_stdlib raap
          - ruby: "4.0"
            job: typecheck_test
    env:
      RANDOMIZE_STDLIB_TEST_ORDER: "true"
    steps:
      - uses: actions/checkout@v6
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler: none
      - name: Set working directory as safe
        run: git config --global --add safe.directory $(pwd)
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libdb-dev curl autoconf automake m4 libtool python3
      - name: Update rubygems & bundler
        run: |
          ruby -v
          gem update --system
      - name: bundle config set with
        run: |
          echo "NO_MINITEST=true" >> $GITHUB_ENV
          bundle config set --local without 'minitest'
        if: ${{ contains(matrix.ruby, 'head') }}
      - name: bundle config set force_ruby_platform true if head
        if: ${{ contains(matrix.ruby, 'head') }}
        run: |
          bundle config set force_ruby_platform true
      - name: Skip installing type checkers
        if: ${{ ! contains(matrix.job, 'typecheck_test') }}
        run: |
          bundle config set without 'typecheck_test'
      - name: bin/setup
        run: |
          bin/setup
      - name: Run test
        run: |
          bundle exec rake ${{ matrix.job }}
  C99_compile:
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        ruby: ['4.0', head]
    steps:
      - uses: actions/checkout@v6
      - name: Install dependencies
        run: |
          brew install ruby-build
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler: none
      - name: Set working directory as safe
        run: git config --global --add safe.directory $(pwd)
      - name: Update rubygems & bundler
        run: |
          ruby -v
          gem update --system
      - name: clang version
        run: clang --version
      - name: bundle config set force_ruby_platform true if head
        if: ${{ contains(matrix.ruby, 'head') }}
        run: |
          bundle config set force_ruby_platform true
      - name: bin/setup
        run: |
          bin/setup
      - run: bundle exec rake clean compile_c99
