name: Ruby

on:
  push:
    branches:
      - master
  pull_request: {}

jobs:
  test:
    runs-on: "ubuntu-latest"
    strategy:
      matrix:
        container_tag:
        - master-nightly-focal
        - 3.0-focal
        - 2.7-bionic
        - 2.6-bionic
        job:
        - test
        - stdlib_test
        - rubocop validate test_doc build test_generate_stdlib
        - lexer confirm_lexer
        - lexer compile
        exclude:
        - container_tag: master-nightly-focal
          job: confirm_lexer
        - container_tag: 2.6-bionic
          job: stdlib_test
    container:
      image: rubylang/ruby:${{ matrix.container_tag }}
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        apt-get update
        apt-get install -y libdb-dev curl autoconf automake m4 libtool
    - name: Install Re2c
      if: contains(matrix.job, 'lexer')
      run: |
        cd /tmp
        curl -L https://github.com/skvadrik/re2c/archive/refs/tags/2.2.tar.gz > re2c-2.2.tar.gz
        tar xf re2c-2.2.tar.gz
        cd re2c-2.2
        autoreconf -i -W all
        ./configure
        make
        make install
    - name: Update rubygems & bundler
      run: |
        ruby -v
        gem update --system
    - name: bundle config set with
      run: |
        echo "NO_MINITEST=true" >> $GITHUB_ENV
        bundle config set --local without 'minitest'
      if: "contains(matrix.container_tag, 'master-nightly')"
    - name: bin/setup
      run: |
        bin/setup
    - name: Run test
      run: |
        bundle exec rake ${{ matrix.job }}
