name: Valgrind

on:
  push:
    branches:
      - master
    paths:
      - "ext/**"
      - "include/**"
      - "src/**"
  pull_request:
    paths:
      - "ext/**"
      - "include/**"
      - "src/**"
  merge_group: {}

jobs:
  valgrind:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.4"
          bundler-cache: none
      - name: Set working directory as safe
        run: git config --global --add safe.directory $(pwd)
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libdb-dev curl autoconf automake m4 libtool python3 valgrind
      - name: Update rubygems & bundler
        run: |
          ruby -v
          gem update --system
      - name: bin/setup
        run: |
          bin/setup
      - run: bundle exec rake test:valgrind
        env:
          RUBY_FREE_AT_EXIT: 1
